config/routes.rb
Rails.application.routes.draw do
  # mount ActionCable.server => '/cable'
  get '/cable' => 'cable#index'
  ActiveAdmin.routes(self)
  scope '(:locale)', locale: /en|ua/ do
    root 'settings#index'
    get 'destroy/sessions' => 'sessions#destroy'
    get 'users/confirm_registration'
    get 'settings/registrations/koatuu'
    get 'settings/companies/change_company'
    get 'sessions/set_language'

    resources :messages, only: [:new, :create]

    resources :conversations, only: [:index, :show, :destroy] do
      member do
        post :reply
        post :forward
        post :restore
      end
      collection do
        delete :empty_trash
      end
    end
    resources :sessions, only: [:new, :create]
    resources :users, only: [:new, :create, :update] do
      collection do
        get :recipients
      end
    end
    resources :settings, only: [:index, :show]
    resources :password_resets
    resources :money, only: [:index] do
      collection { get :search, to: 'money#index' }
    end
    resources :delegates, only: [:create, :destroy, :update]
    resources :sales, only: [:index]
    resources :purchases, only: [:index]
    resources :contracts
    resources :accounting_accounts, except: :edit
    resources :guide_units, except: :edit
    resources :tool_equipments, only: :index
    resources :personnels, only: :index

    namespace 'settings' do
      resources :companies, only: [:new, :create, :update]
      resources :registrations, only: [:new, :create, :update]
      resources :officials, only: [:new, :create, :update]
      resources :bank_accounts, only: [:new, :create, :update]

      post 'companies/add_existing_company'
    end

    namespace 'money' do
      namespace :currency_transactions do
        resources :payment_orders
        resources :orders
      end
      resources :currencies
      resources :banks
      resources :credits
      resources :accounts
      resources :cashiers
      resources :articles
      resources :registers
      resources :exchange_rates
      resources :currency_transactions
    end

    namespace 'purchases' do
      resources :counterparties
      resources :nomenclatures, except: :edit
      resources :products
    end

    namespace 'tool_equipments' do
      resources :main_tools
    end

    namespace 'personnels' do
      resources :departments
      resources :positions
      resources :employees
    end
    resources :chat do
      collection do
        get :list
      end
      member do
        put :change_name
      end
    end
    resources :chat_messages
    get '*path', to: 'application#page_not_found'
  end
end

app/models/counterparty.rb
class Counterparty < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :company
  belongs_to :bank
  has_many :contracts
  has_many :money_registers
  has_many :payment_orders
  has_many :products

  validates :name, :title, :adress, presence: true
  validates_numericality_of :edrpo, :mfo, :account
end

app/controllers/purchases/counterparties_controller.rb
module Purchases
  class CounterpartiesController < ApplicationController
    before_action :redirect_to_new_session
    before_action :company?, only: :new
    before_action :set_counterparty, only: [:update, :destroy]
    before_action :define_counterparty, only: [:new, :create]
    before_action :all_counterparties, only: [:index, :new, :create]

    def index
      counterparties = @counterparties.map { |counterparty| { value: counterparty.id, text: counterparty.name } }
      render json: counterparties, status: 200
    end

    def new
      respond_to do |format|
        format.js
      end
    end

    def create
      @counterparty = Counterparty.new counterparty_params
      flash.now[:error] = t('validation.errors.all_fields') unless @counterparty.save
      respond_to do |format|
        format.js
      end
    end

    def update
      respond_to do |format|
        if @counterparty.update(counterparty_params)
          format.json { head :no_content }
        else
          format.json { render json: @counterparty.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @counterparty.destroy
      respond_to do |format|
        format.js
      end
    end

    private

    def set_counterparty
      @counterparty = Counterparty.find(params[:id])
    end

    def counterparty_params
      params.require(:counterparty).permit(:name,
                                           :title,
                                           :resident,
                                           :edrpo,
                                           :adress,
                                           :account,
                                           :bank_id,
                                           :mfo).merge!(company_id: current_user.current_company.id)
    end

    def define_counterparty
      @counterparty ||= Counterparty.new
    end

    def all_counterparties
      @counterparties ||= current_user.counterparties.order('counterparties.created_at DESC')
    end
  end
end

app/controllers/purchases/nomenclatures_controller.rb
module Purchases
  class NomenclaturesController < ApplicationController
    before_action :redirect_to_new_session
    before_action :find_nomenclature, only: [:destroy, :update]
    before_action :all_nomenclatures, only: [:index, :create]
    before_action :define_nomenclature, only: [:index, :create]
    before_action :subclasses_of_nomenclature, only: :index

    def index
      if params[:paginate]
        render partial: 'purchases/nomenclatures/paginate'
      else
        respond_to do |format|
          format.js
          format.html { render layout: false }
        end
      end
    end

    def create
      @nomenclature.update(nomenclatures_params)
      flash.now[:error] = t('validation.errors.all_fields') unless @nomenclature.save
      respond_to { |format| format.js }
    end

    def update
      respond_to do |format|
        if @nomenclature.update(nomenclatures_params)
          format.json { head :no_content }
        else
          format.json { render json: @nomenclature.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      flash.now[:error] = t('validation.errors.delete_error') unless @nomenclature.destroy
      respond_to { |format| format.js }
    end

    private

    def define_nomenclature
      @nomenclature = Nomenclature.new
    end

    def find_nomenclature
      @nomenclature = Nomenclature.find(params[:id])
    end

    def nomenclatures_params
      params.require(:nomenclature).permit!.merge(company_id: current_company.id)
    end

    def all_nomenclatures
      @nomenclatures = current_company.nomenclatures.by_type(params[:type])
                                      .page(params[:page])
    end

    def subclasses_of_nomenclature
      @subclasses = Nomenclature.subclasses
    end
  end
end

app/controllers/purchases/products_controller.rb
class Purchases::ProductsController < ApplicationController
  before_action :redirect_to_new_session
  before_action :find_product, only: [:update, :destroy]
  before_action :product, only: [:new, :create]

  layout false

  def index
    @products = current_company.products.order('products.created_at DESC')
  end

  def create
    @product.update(product_params)
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.json { head :no_content }
      else
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
  end

  private

  def product_params
    params.require(:product).permit!
  end

  def find_product
    @product = Product.find(params[:id])
  end

  def product
    @product = current_company.products.new(number: current_company.products.count + 1)
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :redirect_to_new_session
end

app/helpers/counterparties_helper.rb
module CounterpartiesHelper
  def counterparty_page?
    counterparty = params[:counterparty]
    %w(costs income).include?(counterparty[:page]) || 'out' == counterparty[:type]
  end
end

app/views/purchases/counterparties/_counterparties.html.slim
.modal-dialog
  .modal-content
    .modal-header
      .row
        .col.col-lg-12
          button.close aria-hidden="true" data-dismiss="modal" type="button"&times;
      .row
        .col.col-lg-12
          h4#myModalLabel.modal-title = t('purchases.counterparties')
          .notification.error style='display:none;'
          = link_to '', '#', class: 'add_new glyphicon glyphicon-plus-sign', id: 'add_new_counterparty'
    .modal-body
      .row
        .col.col-lg-12
          #counterparty_form
          #counterparty_list

app/views/purchases/counterparties/_form.html.slim
  = form_for [:purchases, @counterparty], method: :post, remote: :true do |f|
    .row
      .col-lg-3
        = f.label t('block_title.title')
        = f.text_field :title
      .col-lg-3
        = f.label t('counterparty.name')
        = f.text_field :name
      .col-lg-3
        = f.label t('counterparty.address')
        = f.text_field :adress
      .col-lg-3
        = f.label t('counterparty.edrpo')
        = f.text_field :edrpo, :class => 'number', maxlength: 8
    .row
      .col-lg-3
        = f.label t('counterparty.account')
        = f.text_field :account, :class => 'number'
      .col-lg-3
        = f.label t('money.accounts.bank')
        = select_tag 'counterparty[bank_id]', '', class: 'banks', data: { select: false, type: 'new'}
      .col-lg-3
        = f.label t('bank_accounts.mfo')
        = f.text_field :mfo, :class => 'number', maxlength: 8
      .col-lg-3
        = f.label t('counterparty.is_resident?'), class: 'resident_label'
        = f.check_box :resident
        - unless params[:page].nil?
          =f.hidden_field :page, value: params[:page]
    .row
      .col-lg-3
        = f.submit t('buttons.add')

app/views/purchases/counterparties/_list.html.slim
table.table
  thead
    tr
      th
        = t('block_title.title')
      th
        = t('counterparty.name')
      th
        = t('counterparty.resident')
      th
        = t('counterparty.edrpo')
      th
        = t('bank_accounts.mfo')
      th
        = t('counterparty.account')
      th
        = t('money.accounts.bank')
      th
        = t('counterparty.address')

  tbody
    - @counterparties.each do |counterparty|
      tr id="counterparty_#{counterparty.id}"
        td
          = link_to  counterparty.title, '#', data: { name: :title, type: 'textarea', placement: 'bottom', pk: counterparty, model: :counterparty, url: purchases_counterparty_path(counterparty.id), xeditable: true }
        td
          = link_to  counterparty.name, '#', data: { name: :name, type: 'textarea', placement: 'bottom', pk: counterparty, model: :counterparty, url: purchases_counterparty_path(counterparty.id), xeditable: true } 
        td
          = check_box_tag '', '', counterparty.resident, :class =>'counterparty_resident', data: { id: counterparty.id }
        td
          = link_to  counterparty.edrpo, '#', data: { name: :edrpo, placement: 'bottom', pk: counterparty, model: :counterparty, url: purchases_counterparty_path(counterparty.id), xeditable: true }
        td
          = link_to  counterparty.mfo, '#', data: { name: :mfo, placement: 'bottom', pk: counterparty, model: :counterparty, url: purchases_counterparty_path(counterparty.id), xeditable: true }
        td
          = link_to  counterparty.account, '#', data: { name: :account, placement: 'bottom', pk: counterparty, model: :counterparty, url: purchases_counterparty_path(counterparty.id), xeditable: true }
        td
          = link_to counterparty.bank.name, '#', data: { name: :bank_id, pk: counterparty, value: counterparty.bank_id, placement: 'bottom', model: :counterparty, url:  purchases_counterparty_path(counterparty.id) }, class: 'change_bank'
        td
          = link_to  counterparty.adress, '#', data: { name: :adress, type: 'textarea', placement: 'bottom', pk: counterparty, model: :counterparty, url: purchases_counterparty_path(counterparty.id), xeditable: true }
        td style='width:40px;' 
          = application_present.destroy_link purchases_counterparty_path(counterparty)

app/views/purchases/counterparties/create.js.slim
- if flash[:error]
  | $('#counterparty .notification.error').show().text("#{flash[:error]}").fadeOut(5000);
- else
  - if params[:counterparty][:page].nil?
    | $('#counterparty_list').html("#{j render 'purchases/counterparties/list'}");
    | $('#new_counterparty').hide()[0].reset();
    | editableStart();
    | Counterparties.checkResident();
    | $.unblockUI();
  - else
    - if counterparty_page?
      | $('.counterparty_select').html("#{j select_tag 'money_register[counterparty_id]', '', class: 'company_counterparties', data: { select: false, type: 'new',path: new_purchases_counterparty_path, id: current_user.current_company.id, select: false, page: params[:counterparty][:page]}}");
      | $('.contract_select').html("#{j select_tag 'money_register[contract_id]', '', class: 'counterparty_contracts' , data: { status: :new, select: false, path: new_contract_path, page: params[:counterparty][:page] }}");
      | Contracts.hideContract();
    -elsif params[:counterparty][:page] == "null"
      | $('.counterparty_select').html("#{j select_tag 'contract[counterparty_id]', '', class: 'company_counterparties', data: { select: false, type: 'new', path: new_purchases_counterparty_path, id: current_user.current_company.id, page: params[:counterparty][:page]}}");
    - else
      | $('#contract_form').html("#{j render 'contracts/form'}");
      | Contracts.loadPlugins();
    | $('#counterparty').modal('hide');

app/views/purchases/counterparties/destroy.js.slim
| $("#counterparty_#{params[:id]}").remove();

app/views/purchases/counterparties/index.js.slim
-if params[:page].nil?
  | $('#counterparty').html("#{j render 'purchases/counterparties/counterparties'}").modal('show');
  | $('#counterparty_form').html("#{j render 'purchases/counterparties/form'}");
  | $('#new_counterparty').hide();
  | openform();
  | $('#counterparty_list').html("#{j render 'purchases/counterparties/list'}");
  | editableStart();
  | checkResident();
-else
  | $('#counterparty').html("#{j render 'purchases/counterparties/counterparties'}").modal('show');
  | $('#counterparty_form').html("#{j render 'purchases/counterparties/form'}");
| LoadPluginsCounterparty();

app/views/purchases/counterparties/new.js.slim
-if params[:page].nil?
  | $('#counterparty').html("#{j render 'purchases/counterparties/counterparties'}").modal('show');
  | $('#counterparty_form').html("#{j render 'purchases/counterparties/form'}");
  | $('#new_counterparty').hide();
  | openForm('new_counterparty', 'add_new_counterparty');
  | $('#counterparty_list').html("#{j render 'purchases/counterparties/list'}");
  | editableStart();
  | Counterparties.checkResident();
-else
  | $('#counterparty').html("#{j render 'purchases/counterparties/counterparties'}").modal('show');
  | $('#counterparty_form').html("#{j render 'purchases/counterparties/form'}");
  | $('#add_new_counterparty').remove();
| Counterparties.loadPluginsCounterparty();