config/routes.rb
Rails.application.routes.draw do
  # mount ActionCable.server => '/cable'
  get '/cable' => 'cable#index'
  ActiveAdmin.routes(self)
  scope '(:locale)', locale: /en|ua/ do
    root 'settings#index'
    get 'destroy/sessions' => 'sessions#destroy'
    get 'users/confirm_registration'
    get 'settings/registrations/koatuu'
    get 'settings/companies/change_company'
    get 'sessions/set_language'

    resources :messages, only: [:new, :create]

    resources :conversations, only: [:index, :show, :destroy] do
      member do
        post :reply
        post :forward
        post :restore
      end
      collection do
        delete :empty_trash
      end
    end
    resources :sessions, only: [:new, :create]
    resources :users, only: [:new, :create, :update] do
      collection do
        get :recipients
      end
    end
    resources :settings, only: [:index, :show]
    resources :password_resets
    resources :money, only: [:index] do
      collection { get :search, to: 'money#index' }
    end
    resources :delegates, only: [:create, :destroy, :update]
    resources :sales, only: [:index]
    resources :purchases, only: [:index]
    resources :contracts
    resources :accounting_accounts, except: :edit
    resources :guide_units, except: :edit
    resources :tool_equipments, only: :index
    resources :personnels, only: :index

    namespace 'settings' do
      resources :companies, only: [:new, :create, :update]
      resources :registrations, only: [:new, :create, :update]
      resources :officials, only: [:new, :create, :update]
      resources :bank_accounts, only: [:new, :create, :update]

      post 'companies/add_existing_company'
    end

    namespace 'money' do
      namespace :currency_transactions do
        resources :payment_orders
        resources :orders
      end
      resources :currencies
      resources :banks
      resources :credits
      resources :accounts
      resources :cashiers
      resources :articles
      resources :registers
      resources :exchange_rates
      resources :currency_transactions
    end

    namespace 'purchases' do
      resources :counterparties
      resources :nomenclatures, except: :edit
      resources :products
    end

    namespace 'tool_equipments' do
      resources :main_tools
    end

    namespace 'personnels' do
      resources :departments
      resources :positions
      resources :employees
    end
    resources :chat do
      collection do
        get :list
      end
      member do
        put :change_name
      end
    end
    resources :chat_messages
    get '*path', to: 'application#page_not_found'
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :redirect_to_new_session
  before_action :mailbox
  before_action :current_conversation, except: [:index, :empty_trash]
  before_action :current_box, only: [:index, :forward, :show]

  def index
    @conversations = mailbox_type.paginate(page: params[:page], per_page: 10)
  end

  def show
    render 'forward' if params[:forward]
    @conversation.mark_as_read(current_user)
  end

  def destroy
    @conversation.move_to_trash(current_user)
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  def restore
    @conversation.untrash(current_user)
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  def reply
    @conversation.subject.insert(0, ' RE: ')
    current_user.reply_to_conversation(@conversation, params[:body])
    redirect_to conversation_path(@conversation)
  end

  def forward
    @conversation.subject.insert(0, ' FW: ')
    recipients = recipients_emails(params[:recipients])
    conversation = current_user.send_message(recipients, current_message, @conversation.subject).conversation
    redirect_to conversation_path(conversation)
  end

  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private

  def recipients_emails(params)
    User.where(id: params.split(','))
  end

  def current_box
    @box = params[:box].blank? ? 'inbox' : params[:box]
  end

  def current_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end

  def mailbox
    @mailbox ||= current_user.mailbox
  end

  def current_message
    body = "#{params[:body]}\n\n"
    @conversation.receipts_for(current_user).each do |receipt|
      body += format_conversation_receipt(receipt)
    end
    body
  end

  def format_conversation_receipt(receipt)
    format_time = receipt.message.created_at.strftime('%-d %B %Y, %H:%M:%S')
    format_email = "#{@conversation.originator.email} #{t('conversations.sender_write')}"
    format_body = "#{receipt.message.body}\n\n"
    "0 #{format_time} #{format_email} #{format_body}"
  end

  def mailbox_type
    if @box.eql? 'inbox'
      @mailbox.inbox
    elsif @box.eql? 'sent'
      @mailbox.sentbox
    else
      @mailbox.trash
    end
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.casecmp(current_box).zero?
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
end

app/views/conversations/_conversation.html.slim
li class="list-group-item clearfix" id= "conversation-#{conversation.id}" data-read="#{conversation.is_unread?(current_user)}"
  div class="btn-group-vertical pull-right"
        - if conversation.is_trashed?(current_user)
          div class='restore-btn btn-xs btn-info'  id="restore-#{conversation.id}" = t('conversations.restore')
        - else
          div class='trash-btn btn-xs btn-danger' id="trash-#{conversation.id}" = t('conversations.trash')
  = link_to conversation_path(conversation), class: "testspan"
    div
      = render partial: "conversation_#{box}", locals: { conversation: conversation }
      br
        span class="message-subject"
          = conversation.subject
      p
        span class="message-body"
          = conversation.last_message.body[0, 75]
        small
          span class="message-date"
            = conversation.last_message_data

app/views/conversations/_conversation_inbox.html.slim
says from: 
span class="message-sender"
  = conversation.originator.email

app/views/conversations/_conversation_sent.html.slim
says to: 
span class="message-recipient"
  - conversation.participants.each do |recipient|
    - unless recipient == current_user
      = recipient.email + ', '

app/views/conversations/forward.html.slim
h1 = t('conversations.conversation')

div class="panel panel-default"
  div class="panel-heading"
    says FW: 
    = @conversation.subject
  div class="panel-body"
    - @conversation.receipts_for(current_user).reverse_each do |receipt|
      div class="panel-message"
        - message = receipt.message
        span class="panel-info"
          says from: 
          = message.sender.email
          small
            br
            says  at (
            = message.created_at.strftime("%-d %B %Y, %H:%M:%S")
            says )
        br
        = simple_format(message.body)

= form_tag forward_conversation_path(@conversation), method: :post do
  div class="form-group"
    = text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...'
    = label_tag 'recipients', t('conversations.choose_recipients')
    = hidden_field_tag 'recipients'
  = submit_tag t('conversations.send_message'), class: 'btn btn-primary'

app/views/conversations/index.html.slim
div class="clean-trash"
  - if @box == 'trash'
    p
      h1 = t('conversations.trash')
      div id="empty-btn"
        =link_to t('conversations.empty_trash'), empty_trash_conversations_path, class: 'btn btn-danger', method: :delete, remote: true
  -elsif @box == 'inbox'
    p
      h1 = t('conversations.inbox')
  -else
    p
      h1 = t('conversations.sent')

ul class="list-group" id="messages-list"
  = render partial: 'conversations/conversation', collection: @conversations, locals: { box: @box }
= will_paginate

app/views/conversations/show.html.slim
h1 = t('conversations.conversation')

div class="panel panel-default"
  div class="panel-heading"
    = @conversation.subject
    = link_to 'forward', conversation_path(@conversation, :forward => true), class: "btn forward btn-xs btn-success"
  div class="panel-body"
    - @conversation.receipts_for(current_user).reverse_each do |receipt|
      div class="panel-message"
        - message = receipt.message
        div class="panel-info"
          says from: 
          = message.sender.email
          small
            br
            says  at (
            = message.created_at.strftime("%-d %B %Y, %H:%M:%S")
            says )
        br
        = simple_format(message.body)
= form_tag reply_conversation_path(@conversation), method: :post do
  div class="form-group"
    = text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true
  = submit_tag t('conversations.send_message'), class: 'btn btn-primary'