config/routes.rb
Rails.application.routes.draw do
  # mount ActionCable.server => '/cable'
  get '/cable' => 'cable#index'
  ActiveAdmin.routes(self)
  scope '(:locale)', locale: /en|ua/ do
    root 'settings#index'
    get 'destroy/sessions' => 'sessions#destroy'
    get 'users/confirm_registration'
    get 'settings/registrations/koatuu'
    get 'settings/companies/change_company'
    get 'sessions/set_language'

    resources :messages, only: [:new, :create]

    resources :conversations, only: [:index, :show, :destroy] do
      member do
        post :reply
        post :forward
        post :restore
      end
      collection do
        delete :empty_trash
      end
    end
    resources :sessions, only: [:new, :create]
    resources :users, only: [:new, :create, :update] do
      collection do
        get :recipients
      end
    end
    resources :settings, only: [:index, :show]
    resources :password_resets
    resources :money, only: [:index] do
      collection { get :search, to: 'money#index' }
    end
    resources :delegates, only: [:create, :destroy, :update]
    resources :sales, only: [:index]
    resources :purchases, only: [:index]
    resources :contracts
    resources :accounting_accounts, except: :edit
    resources :guide_units, except: :edit
    resources :tool_equipments, only: :index
    resources :personnels, only: :index

    namespace 'settings' do
      resources :companies, only: [:new, :create, :update]
      resources :registrations, only: [:new, :create, :update]
      resources :officials, only: [:new, :create, :update]
      resources :bank_accounts, only: [:new, :create, :update]

      post 'companies/add_existing_company'
    end

    namespace 'money' do
      namespace :currency_transactions do
        resources :payment_orders
        resources :orders
      end
      resources :currencies
      resources :banks
      resources :credits
      resources :accounts
      resources :cashiers
      resources :articles
      resources :registers
      resources :exchange_rates
      resources :currency_transactions
    end

    namespace 'purchases' do
      resources :counterparties
      resources :nomenclatures, except: :edit
      resources :products
    end

    namespace 'tool_equipments' do
      resources :main_tools
    end

    namespace 'personnels' do
      resources :departments
      resources :positions
      resources :employees
    end
    resources :chat do
      collection do
        get :list
      end
      member do
        put :change_name
      end
    end
    resources :chat_messages
    get '*path', to: 'application#page_not_found'
  end
end

app/views/layouts/authorized/_companies_list.html.slim
- unless company.id == current_user.current_company_id
  = link_to settings_companies_change_company_path(company_id: company.id),
      :'data-id' => company.id
    .col-md-12.text-center
      li
        = company.full_name
      li.divider role="presentation"

app/views/layouts/authorized/_index.html.slim
= content_for :authorized do
  body.pace-done
    #wrapper
      = render 'layouts/authorized/left_bar'
      = render 'layouts/authorized/top_bar'

app/views/layouts/authorized/_left_bar.html.slim
nav.navbar-default.navbar-static-side role='navigation'
  .sidebar-collapse
    ul#side-menu.nav style='display: block;' class='nav'
      li.nav-header
        .dropdown.profile-element style="#{cookies['leftBar'] == '45' ? 'display: none;' : ''}"
          h3
            | Active Books
      li
        = application_present.nav_link_to(root_path, 'fa-building', t('navigation.main'))
      li
        li#messages-link
          - if current_user.mailbox.inbox({:read => false}).present?
            = application_present.nav_link_to('#', 'fa fa-comments', t('conversations.messages') + ' ' +  image_tag("chat-online.png"))
          - else
            = application_present.nav_link_to('#', 'fa fa-comments', t('conversations.messages'))
        ul#messages-menu style='display: none;' class='nav'
          li class="dropdown-message"
            = application_present.nav_link_to(new_message_path, 'fa fa-plus', t('conversations.new_message'))
          li class="dropdown-message"
            - if current_user.mailbox.inbox({:read => false}).present?
              = application_present.nav_link_to(conversations_path(:box => "inbox"), 'fa fa-envelope-o', t('conversations.inbox') + ' (' + current_user.mailbox.inbox({:read => false}).count.to_s + ')')
            - else
              = application_present.nav_link_to(conversations_path(:box => "inbox"), 'fa fa-envelope-o', t('conversations.inbox'))
          li class="dropdown-message"
            = application_present.nav_link_to(conversations_path(:box => "sent"), 'fa fa-pencil-square-o', t('conversations.sent'))
          li class="dropdown-message"
            = application_present.nav_link_to(conversations_path(:box => "trash"), 'fa fa-trash', t('conversations.trash'))
      li
        = application_present.nav_link_to(money_index_path, 'fa-money', t('navigation.money'))
      li
        = application_present.nav_link_to(purchases_path, 'fa-pie-chart', t('navigation.purchases'))
      li
        = application_present.nav_link_to(tool_equipments_path, 'fa fa-wrench', t('navigation.tools_equipment'))
      li
        = application_present.nav_link_to(personnels_path, 'fa fa-users', t('personnels.personnel'))

app/views/layouts/authorized/_top_bar.html.slim
#page-wrapper.gray-bg.dashbard-1 style="margin-left: #{cookies['leftBar']}px"
  .row.border-bottom
    .nav.navbar-static-top role='navigation' style='margin-bottom: 0;'
      .navbar-header
        #path data={ accounts: money_accounts_path, articles: money_articles_path, banks: money_banks_path, contracts: contracts_path, counterparties: purchases_counterparties_path, registers: money_registers_path, currensies: money_currencies_path, orders: money_currency_transactions_orders_path, main_tools: tool_equipments_main_tools_path, accounting_account: accounting_accounts_path, guide_units: guide_units_path, nomenclatures: purchases_nomenclatures_path, departments: personnels_departments_path, positions: personnels_positions_path, employees: personnels_employees_path }
        .row
          .col-md-2
            a.navbar-minimalize.minimalize-styl-2.btn.btn-primary href='#'
              i.fa.fa-bars
          .col-md-10
            p.current-company-top
            - if current_user.companies.size > 1
              = current_user.current_company_full_name
              p.change-current-company data-target="#change-company" data-toggle="modal"
                  = t('change_current_company')
              .row
                .col-md-12
                  = render 'shared/change_company_modal'
      ul.nav.navbar-top-links.navbar-right
        li
          = link_to '', sessions_set_language_path(locale: 'ua'), class: 'ua-language'
        li
          = link_to '', sessions_set_language_path(locale: 'en'), class: 'en-language'
        li
          span.m-r-sm.text-muted
            = current_user.email
        li.dropdown
          = link_to '#', data: { toggle: 'dropdown' }, class: 'dropdown-toggle', role: 'button', aria: {expanded: 'false' }
            i.fa.fa-cog
            = t('settings')
          ul.dropdown-menu.settings role='menu' aria-labelledby='dropdownMenu1'
            li
              = link_to t('buttons.new_company'), new_settings_company_path
            - if current_user.current_company
              li role='presentation'
                = link_to t('settings'), setting_path(current_user.current_company_id)
              li.divider
              li.dropdown-submenu
                = link_to t('money.references'), '#', tabindex: '-1'
                ul.dropdown-menu
                  li
                    =link_to t('accounting_accounts.accounts'), accounting_accounts_path, remote:true
                  li
                    = link_to t('buttons.currency'), money_currencies_path, remote: true, type: :get
                  li
                    = link_to t('buttons.exchange_rates'), money_exchange_rates_path, remote: true, type: :get
                  li
                    = link_to t('buttons.banks'), money_banks_path(page: :banks), remote: true
                  li
                    = link_to t('purchases.counterparties'), new_purchases_counterparty_path, remote: true, type: :get
                  li
                    = link_to t('contract.contracts'), new_contract_path, remote: true, type: :get
                  li
                    = link_to t('guide_units'), guide_units_path, remote: true
                  li
                    = link_to t('tool_equipments.main_tools'), tool_equipments_main_tools_path(type: 'MainTool::Building'), remote: true
                  li
                    = link_to t('purchases.nomenclature'),  purchases_nomenclatures_path(type: 'Nomenclature::Equipment'), remote: true
                  li
                    = link_to t('personnels.departments'),  personnels_departments_path(container: :modal), remote: true
                  li
                    = link_to t('personnels.positions'),  personnels_positions_path(container: :modal), remote: true
                  li
                    = link_to t('personnels.employees'),  personnels_employees_path(container: :modal), remote: true
        li
          = link_to destroy_sessions_path
            i.fa.fa-sign-out
            = t('top_bar.signout')

  .wrapper.wrapper-content.animated.fadeInRight
    .row
      .col-lg-12
        .ibox.white-bg
          #error
          = yield
          #companyAccount.modal.fade aria-hidden="true" aria-labelledby="basicModal" role="dialog" tabindex="-1"
          #contracts.modal.fade aria-hidden='true' aria-labelledby='basicModal' role='dialog' tabindex='-1'
          #counterparty.modal.fade aria-hidden='true' aria-labelledby='basicModal' role='dialog' tabindex='-1'
          #companyCurrency.modal.fade aria-hidden='true' aria-labelledby='basicModal' role='dialog' tabindex='-1'
          #moneyCurrency.modal.fade aria-hidden='true' aria-labelledby='basicModal' role='dialog' tabindex='-1'
          #companyBanks.modal.fade aria-hidden='true' aria-labelledby='basicModal' role='dialog' tabindex='-1'
          #accounting_accounts.modal.fade aria-hidden='true' aria-labelledby='basicModal' role='dialog' tabindex='-1'
          #guide_units.modal.fade aria-hidden='true' aria-labelledby='basicModal' role='dialog' tabindex='-1'
          #main_tools.modal.fade aria-hidden='true' aria-labelledby='basicModal' role='dialog' tabindex='-1'
          #nomenclatures.modal.fade aria-hidden='true' aria-labelledby='basicModal' role='dialog' tabindex='-1'
          #departments_modal.modal.fade aria-hidden="true" aria-labelledby="basicModal" role="dialog" tabindex="-1"
          #positions_modal.modal.fade aria-hidden="true" aria-labelledby="basicModal" role="dialog" tabindex="-1"
          #employees_modal.modal.fade aria-hidden="true" aria-labelledby="basicModal" role="dialog" tabindex="-1"
          #chat_modal.modal.fade aria-hidden="true" aria-labelledby="basicModal" role="dialog" tabindex="-1"