config/routes.rb
Rails.application.routes.draw do
  # mount ActionCable.server => '/cable'
  get '/cable' => 'cable#index'
  ActiveAdmin.routes(self)
  scope '(:locale)', locale: /en|ua/ do
    root 'settings#index'
    get 'destroy/sessions' => 'sessions#destroy'
    get 'users/confirm_registration'
    get 'settings/registrations/koatuu'
    get 'settings/companies/change_company'
    get 'sessions/set_language'

    resources :messages, only: [:new, :create]

    resources :conversations, only: [:index, :show, :destroy] do
      member do
        post :reply
        post :forward
        post :restore
      end
      collection do
        delete :empty_trash
      end
    end
    resources :sessions, only: [:new, :create]
    resources :users, only: [:new, :create, :update] do
      collection do
        get :recipients
      end
    end
    resources :settings, only: [:index, :show]
    resources :password_resets
    resources :money, only: [:index] do
      collection { get :search, to: 'money#index' }
    end
    resources :delegates, only: [:create, :destroy, :update]
    resources :sales, only: [:index]
    resources :purchases, only: [:index]
    resources :contracts
    resources :accounting_accounts, except: :edit
    resources :guide_units, except: :edit
    resources :tool_equipments, only: :index
    resources :personnels, only: :index

    namespace 'settings' do
      resources :companies, only: [:new, :create, :update]
      resources :registrations, only: [:new, :create, :update]
      resources :officials, only: [:new, :create, :update]
      resources :bank_accounts, only: [:new, :create, :update]

      post 'companies/add_existing_company'
    end

    namespace 'money' do
      namespace :currency_transactions do
        resources :payment_orders
        resources :orders
      end
      resources :currencies
      resources :banks
      resources :credits
      resources :accounts
      resources :cashiers
      resources :articles
      resources :registers
      resources :exchange_rates
      resources :currency_transactions
    end

    namespace 'purchases' do
      resources :counterparties
      resources :nomenclatures, except: :edit
      resources :products
    end

    namespace 'tool_equipments' do
      resources :main_tools
    end

    namespace 'personnels' do
      resources :departments
      resources :positions
      resources :employees
    end
    resources :chat do
      collection do
        get :list
      end
      member do
        put :change_name
      end
    end
    resources :chat_messages
    get '*path', to: 'application#page_not_found'
  end
end

app/models/currency_transaction/sale.rb
class CurrencyTransaction::Sale < CurrencyTransaction; end

app/controllers/money/accounts_controller.rb
module Money
  class AccountsController < ApplicationController
    before_action :redirect_to_new_session
    before_action :set_account, only: [:destroy, :update, :show]
    before_action :define_account, only: [:index, :new]
    before_action :company_account, only: [:index, :create]

    def index
      respond_to do |format|
        format.js
        format.json do
          accounts = params[:currency] ? @accounts.acconts_on_type(params[:currency]) : @accounts
          render json: accounts.map { |account| { value: account.id, text: account.name } }, status: 200
        end
      end
    end

    def new
      respond_to do |format|
        format.js
      end
    end

    def show
      respond_to do |format|
        format.js
      end
    end

    def create
      @account = Account.new account_params
      flash[:error] = t('validation.errors.invalid_data') unless @account.save
      respond_to do |format|
        format.js
      end
    end

    def update
      respond_to do |format|
        if @account.update(account_params)
          format.json { head :no_content }
        else
          format.json { render json: @account.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @account.destroy
      respond_to do |format|
        format.js
      end
    end

    private

    def set_account
      @account = Account.find(params[:id])
    end

    def account_params
      params.require(:account).permit(:name,
                                      :account_type,
                                      :number,
                                      :currency,
                                      :bank_id).merge!(company_id: current_user.current_company.id)
    end

    def define_account
      @account ||= Account.new
    end

    def company_account
      @accounts = current_user.accounts.order('accounts.created_at DESC')
    end
  end
end

app/controllers/money/articles_controller.rb
module Money
  class ArticlesController < ApplicationController
    before_action :redirect_to_new_session
    before_action :set_article, only: [:destroy, :update, :show]
    before_action :define_article, only: :index
    before_action :all_articles, only: [:index, :create]

    def index
      respond_to do |format|
        format.js
        format.json { render json: articles_for_select2, status: 200 }
      end
    end

    def show
      respond_to do |format|
        format.js
      end
    end

    def create
      @article = Article.new article_params
      flash[:error] = t('validation.errors.invalid_data') unless @article.save
      respond_to do |format|
        format.js
      end
    end

    def update
      respond_to do |format|
        if @article.update(article_params)
          format.json { head :no_content }
        else
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @article.destroy
      respond_to do |format|
        format.js
      end
    end

    private

    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:code, :name)
    end

    def define_article
      @article ||= Article.new
    end

    def all_articles
      @articles = Article.all
    end

    def articles_for_select2
      Article.all.map do |article|
        { value: article.id, text: article.name }
      end
    end
  end
end

app/controllers/money/banks_controller.rb
module Money
  class BanksController < ApplicationController
    before_action :redirect_to_new_session
    before_action :find_bank, only: [:destroy, :update, :show]
    before_action :define_bank, only: :index
    before_action :all_banks, only: [:index, :create]

    def index
      respond_to do |format|
        format.js
        format.json { render json: banks_for_select2, status: 200 }
      end
    end

    def show
      respond_to { |format| format.js }
    end

    def create
      @bank = Bank.new bank_params
      flash.now[:error] = t('validation.errors.invalid_data') unless @bank.save
      respond_to { |format| format.js }
    end

    def update
      respond_to do |format|
        if @bank.update(bank_params)
          format.json { head :no_content }
        else
          format.json { render json: @bank.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @bank.assigned? ? flash.now[:error] = t('validation.errors.bank_error') : @bank.destroy
      respond_to { |format| format.js }
    end

    private

    def find_bank
      @bank = Bank.find(params[:id])
    end

    def bank_params
      params.require(:bank).permit!
    end

    def define_bank
      @bank ||= Bank.new
    end

    def all_banks
      @banks = Bank.all
    end

    def banks_for_select2
      Bank.all.map do |bank|
        { value: bank.id, text: bank.name }
      end
    end
  end
end

app/controllers/money/cashiers_controller.rb
module Money
  class CashiersController < ApplicationController
    before_action :redirect_to_new_session
    before_action :set_cashier, only: [:destroy, :update, :show]
    before_action :define_cashier, only: :index
    before_action :company_cashiers, only: [:index, :create]

    def index
      respond_to do |format|
        format.js
      end
    end

    def show
      respond_to do |format|
        format.js
      end
    end

    def create
      @cashier = Cashier.new cashier_params
      flash[:error] = t('validation.errors.invalid_data') unless @cashier.save
      respond_to do |format|
        format.js
      end
    end

    def update
      respond_to do |format|
        if @cashier.update(cashier_params)
          format.json { head :no_content }
        else
          format.json { render json: @cashier.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @cashier.destroy
      respond_to do |format|
        format.js
      end
    end

    private

    def set_cashier
      @cashier = Cashier.find(params[:id])
    end

    def cashier_params
      params.require(:cashier).permit(:name, :currency).merge!(company_id: current_user.current_company.id)
    end

    def define_cashier
      @cashier ||= Cashier.new
    end

    def company_cashiers
      @cashiers = current_user.cashiers
    end
  end
end

app/controllers/money/credits_controller.rb
module Money
  class CreditsController < ApplicationController
    before_action :redirect_to_new_session
    before_action :set_credit, only: [:destroy, :update, :show]
    before_action :define_credit, only: [:index, :create]
    before_action :all_credits, only: [:index, :create]

    def index
      respond_to do |format|
        format.js
      end
    end

    def show
      respond_to do |format|
        format.js
      end
    end

    def create
      if @credit.update_attributes(credit_params)
        @credits.push @credit
      else
        flash[:error] = t('validation.errors.invalid_data')
      end
      respond_to do |format|
        format.js
      end
    end

    def update
      respond_to do |format|
        if @credit.update(credit_params)
          @credits = current_user.current_company.try(:credits)
          format.json { head :no_content }
        else
          format.json { render json: @credit.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @credit.destroy
      respond_to do |format|
        format.js
      end
    end

    private

    def credit_params
      params.require(:credit).permit!
    end

    def set_credit
      @credit = Credit.find(params[:id])
    end

    def define_credit
      @credit ||= current_user.credits.new
    end

    def all_credits
      @credits ||= current_user.try(:credits) || []
    end
  end
end

app/controllers/money/currencies_controller.rb
module Money
  class CurrenciesController < ApplicationController
    before_action :redirect_to_new_session
    before_action :set_currency, only: [:destroy]
    before_action :company_currencies, only: [:index, :create]

    def index
      respond_to do |format|
        format.js
      end
    end

    def create
      currency = current_user.currencies.new currency_params
      flash.now[:error] = t('validation.errors.all_fields') unless currency.save
      @currencies = current_user.currencies
      respond_to do |format|
        format.js
      end
    end

    def destroy
      currency = Currency.find(params[:id])
      render json: { success: currency.destroy }
    end

    private

    def set_currency
      @currency = Currency.find(params[:id])
    end

    def currency_params
      params.require(:currency).permit(:name).merge!(company_id: current_user.current_company.id)
    end

    def company_currencies
      @currencies = current_user.current_company.currencies
    end
  end
end

app/controllers/money/currencies_transactions_controller.rb
module Money
  class CurrenciesTransactionsController < ApplicationController
    before_filter :redirect_to_new_session

    def index
      respond_to do |format|
        format.js
      end
    end
  end
end

app/controllers/money/currency_transactions/orders_controller.rb
class Money::CurrencyTransactions::OrdersController < ApplicationController
  before_action :redirect_to_new_session
  before_action :define_order, only: [:create, :index]
  before_action :all_orders, only: [:create, :index]
  before_action :order, only: :destroy

  def index
    respond_to do |format|
      format.js
      format.json do
        render json: ActiveModel::ArraySerializer.new(@orders,
                                                      each_serializer: OrderSerializer,
                                                      root: nil), status: 200
      end
    end
  end

  def create
    @order.update_attributes order_params
    flash.now[:error] = t('validation.errors.all_fields') unless @order.save
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @order.destroy
    respond_to do |format|
      format.js
    end
  end

  private

  def order
    @order = Order.find(params[:id])
  end

  def define_order
    @order = Order.new
  end

  def order_params
    params.require(:order).permit!.except(:path).merge(company_id: current_company.id)
  end

  def all_orders
    company_orders = current_user.orders.order('orders.created_at DESC')
    @orders = company_orders.orders_by_type(params[:type] || params[:order][:type_order])
  end
end

app/controllers/money/currency_transactions/payment_orders_controller.rb
class Money::CurrencyTransactions::PaymentOrdersController < ApplicationController
  before_action :redirect_to_new_session
  before_action :define_payment_order, only: [:create, :index]
  before_action :payment_order, only: :destroy
  before_action :payment_orders, only: [:index, :create]

  def index
    respond_to do |format|
      format.js
    end
  end

  def create
    @payment_order.update_attributes payment_order_params
    flash.now[:error] = t('validation.errors.all_fields') unless @payment_order.save
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @payment_order.destroy
    respond_to do |format|
      format.js
    end
  end

  private

  def payment_order
    @payment_order = PaymentOrder.find(params[:id])
  end

  def define_payment_order
    @payment_order = PaymentOrder.new
  end

  def payment_order_params
    params.require(:payment_order).permit(:date,
                                          :account_id,
                                          :counterparty_id,
                                          :total,
                                          :article_id,
                                          :currency,
                                          :number,
                                          :type_order).merge!(company_id: current_company.id)
  end

  def payment_orders
    company_payment_orders = current_user.payment_orders
    @payment_orders = company_payment_orders.by_type(params[:type] || params[:payment_order][:type_order])
                                            .order('payment_orders.created_at DESC')
  end
end

app/controllers/money/currency_transactions_controller.rb
module Money
  class CurrencyTransactionsController < ApplicationController
    before_action :redirect_to_new_session
    before_action :define_currency_transaction, only: [:new, :create]
    before_action :currency_transactions, only: [:new, :create]
    before_action :find_currency_transaction, only: :destroy

    def index
      respond_to { |format| format.js }
    end

    def new
      respond_to { |format| format.js }
    end

    def create
      @currency_transaction.update_attributes currency_transaction_params
      flash.now[:error] = t('validation.errors.all_fields') unless @currency_transaction.save
      respond_to { |format| format.js }
    end

    def destroy
      @curency_transaction.destroy
      respond_to { |format| format.js }
    end

    private

    def find_currency_transaction
      @curency_transaction = CurrencyTransaction.find(params[:id])
    end

    def define_currency_transaction
      @currency_transaction = CurrencyTransaction.new
    end

    def currency_transaction_params
      params.require(:currency_transaction).permit!.merge(company_id: current_company.id)
    end

    def currency_transactions
      company_currency_transactions = current_user.currency_transactions.order('currency_transactions.created_at DESC')
      @currency_transactions = company_currency_transactions.by_type(params[:type] || params[:currency_transaction][:type])
    end
  end
end

app/helpers/currency_transactions_helper.rb
module CurrencyTransactionsHelper
  def render_type_of_transaction_link(type)
    link = {
      'Purchase' => (link_to t('buttons.buy_currency'), new_money_currency_transaction_path(type: 'CurrencyTransaction::' + type), remote: true, class: 'btn btn-primary btn-modal').to_s,
      'Sale' => (link_to t('buttons.currency_sale'), new_money_currency_transaction_path(type: 'CurrencyTransaction::' + type), remote: true, class: 'btn btn-primary btn-modal').to_s
    }
    link[type].html_safe
  end

  def render_type_of_order_link(type)
    link = {
      'Purchase' => (link_to t('money.currences_tran.order_p_f_currency'), money_currency_transactions_orders_path(type: 'CurrencyTransaction::' + type), remote: true, class: 'btn btn-primary btn-modal').to_s,
      'Sale' => (link_to t('money.currences_tran.order_s_f_currency'), money_currency_transactions_orders_path(type: 'CurrencyTransaction::' + type), remote: true, class: 'btn btn-primary btn-modal').to_s
    }
    link[type].html_safe
  end

  def render_transaction_title(type)
    title = {
      'CurrencyTransaction::Purchase' => t('buttons.buy_currency'),
      'CurrencyTransaction::Sale' => t('buttons.currency_sale')
    }
    title[type]
  end

  def render_currency_transactions_list(currency_transactions)
    render partial: 'money/currency_transactions/list_transactions', collection: currency_transactions, as: :currency_transaction
  end
end

app/views/money/currency_transactions/_form.html.slim
= form_for [:money, @currency_transaction], method: :post, remote: :true do |f|
  .row
    .col-lg-2
      = f.label t('money.costs.date')
      = f.text_field :date, data: { timePicker: false }
    .col-lg-2
      = f.label t('money.currences_tran.order_p_f_currency')
      = link_to t('buttons.add_new'), money_currency_transactions_orders_path(type: params[:type], path: 'currency_transactions'), remote: true
      #select_order
        = f.select :order_id, {}, {}, { class: 'orders', data: { select: false, type: 'new' } }
    .col-lg-2
      label
        = t('money.accounts.bank')
      input#transaction_bank readonly='readonly'
    .col-lg-2
      label
        = t('money.currency')
      input#transaction_currency readonly='readonly'
    .col-lg-2
      label
        = t('money.order.rate')
      input#transaction_rate readonly='readonly'
    .col-lg-2
      label
        = t('money.costs.total')
      input#transaction_total readonly='readonly'
  .row
    .col-lg-2
      label
        = t('money.order.account_grn')
      input#transaction_account_grn readonly='readonly'
    .col-lg-2
      label
        = t('money.order.account_rate')
      input#transaction_account_rate readonly='readonly'
    .col-lg-2
      label
        = t('money.order.commission')
      input#transaction_commission readonly='readonly'
    .col-lg-2
      label
        = t('money.order.total_grn')
      input#transaction_total_grn readonly='readonly'
    .col-lg-2
      = f.label t('money.order.pension_fund_total')
      .row
        .col-lg-6.padding-right-1
          input#pf_grn.number maxlength='4' placeholder='%'
        .col-lg-6.padding-left-1
          = f.text_field :total_pf, readonly: :readonly, placeholder: t('grn')
    .col-lg-2
      br
      = f.hidden_field :type, value: params[:type]
      = f.submit t('buttons.add')

app/views/money/currency_transactions/_list.html.slim
table.table.noselect
  thead
    tr.bg-grey
      th
        = t('money.costs.date')
      th
        = t('money.currency')
      th
        = t('money.currences_tran.order_p_f_currency')
      th
        = t('money.order.pension_fund_total')
      th
        = t('money.costs.total')
      th
        = t('money.order.rate')
      th
        = t('money.order.commission')
      th
        = t('money.order.total_grn')
      th
        = t('money.order.account_grn')
      th
        = t('money.order.account_rate')
      th
  tbody
     = render_currency_transactions_list(@currency_transactions)

app/views/money/currency_transactions/_list_transactions.html.slim
tr id="curency_transaction_#{currency_transaction.id}"
  td
    = l(currency_transaction.date, format: :long)
  td
    = t(currency_transaction.order_currency)
  td
    = "№(#{currency_transaction.order_id})"
  td
    = currency_transaction.total_pf
  td
    = currency_transaction.order_total
  td
    = currency_transaction.order_rate
  td
    = currency_transaction.order_commission
  td
    = currency_transaction.order_total_grn
  td
    = currency_transaction.grn_account_name
  td
    = currency_transaction.foreign_currency_account_name
  - if can? :destroy, CurrencyTransaction
    td.width-40
      = application_present.destroy_link money_currency_transaction_path(currency_transaction)

app/views/money/currency_transactions/_menu.html.slim
.modal-dialog
  .modal-content
    .modal-header
      .row
        .col.col-lg-12
          button.close aria-hidden="true" data-dismiss="modal" type="button"&times;
      .row
        .col.col-lg-4
          h4#myModalLabel.modal-title = t('money.documents')
        .col.col-lg-4
          h4#myModalLabel.modal-title = t('money.reports')
        .col.col-lg-4
          h4#myModalLabel.modal-title = t('money.references')
    .modal-body
      .row
        .col.col-lg-4
          = render_type_of_order_link(params[:type])
          = link_to t('money.currences_tran.payment_order_out'), money_currency_transactions_payment_orders_path(type: params[:type] + 'Out'), remote: true, class: 'btn btn-primary btn-modal'
          = render_type_of_transaction_link(params[:type])
          = link_to t('money.currences_tran.payment_orders_in'), money_currency_transactions_payment_orders_path(type: params[:type] + 'In'), remote: true, class: 'btn btn-primary btn-modal'
        .col.col-lg-4
          = link_to t('money.currences_tran.turnover_balance'), '#', class: 'btn btn-primary btn-modal'
          = link_to t('money.currences_tran.card_number'), '#', class: 'btn btn-primary btn-modal'
        .col.col-lg-4
          = link_to t('buttons.currency'), money_currencies_path, remote: true, type: :get, class: 'btn btn-primary btn-modal'
          = link_to t('buttons.exchange_rates'), money_exchange_rates_path, remote: true, type: :get, class: 'btn btn-primary btn-modal'

app/views/money/currency_transactions/_modal.html.slim
.modal-dialog
  .modal-content
    .modal-header
      .row
        .col-lg-12
          button.close aria-hidden="true" data-dismiss="modal" type="button"&times;
      .row
        .col-lg-12
          h4#myModalLabel.modal-title = render_transaction_title(params[:type])
          .notification.error
          = link_to '', '#', class: 'add_new glyphicon glyphicon-plus-sign', id: 'add_new_transaction'
    .modal-body
      .row
        .col-lg-12
          #currency_purchases_form
          #currency_purchases_list.scroll-table

app/views/money/currency_transactions/new.js.slim
| $('#currency_purchases').html("#{j render 'money/currency_transactions/modal'}").modal('show');
| $('#currency_purchases_list').html("#{j render 'money/currency_transactions/list'}");
| $('#currency_purchases_form').html("#{j render 'money/currency_transactions/form'}");
| CurrencyTransactions.loadPlugins();